source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload
plug "occivink/kakoune-phantom-selection"
plug "Delapouite/kakoune-text-objects"
plug "https://github.com/h-youhei/kakoune-surround"
plug "alexherbo2/auto-pairs.kak" %{
	enable-auto-pairs
}
evaluate-commands %sh{ colorcol }
hook global WinCreate .* %{
  colorcol-enable
  colorcol-refresh-continuous
}
plug "andreyorst/fzf.kak" config %{
    require-module fzf
    require-module fzf-buffer
    require-module fzf-cd
    require-module fzf-file
    require-module fzf-grep
    require-module fzf-search

    map global user a ': fzf-mode<ret>' -docstring 'fzf'
}  defer fzf %{
    set-option global fzf_terminal_command 'terminal-tab kak -c %val{session} -e "%arg{@}"' 
}
plug 'delapouite/kakoune-buffers' %{
#  map global normal ^ q
#  map global normal <a-^> Q
#  map global normal q b
#  map global normal Q B
#  map global normal <a-q> <a-b>
#  map global normal <a-Q> <a-B>
  map global user g ': pick-buffers<ret>' -docstring 'buffers'
  map global user G ': enter-buffers-mode<ret>' -docstring 'buffers'
  map global user ö ':delete-buffer<ret>'
  # map global user <s-ö> ':delete-buffer!<ret>'
}
plug 'delapouite/kakoune-i3' %{
  # Suggested mapping
  map global user 3 ': enter-user-mode i3<ret>' -docstring 'i3 mode'
}
plug "danr/kakoune-easymotion"
plug "occivink/kakoune-snippets" config %{
    set-option -add global snippets_directories "~/.config/kak/plugins/kakoune-snippet-collection/"
    # some other kakoune-snippets related configurations
}
plug "andreyorst/kakoune-snippet-collection"
# plug "lePerdu/kakboard" %{
    # hook global WinCreate .* %{ kakboard-enable }
# }
plug "JJK96/kakoune-emmet"
map global insert <c-ret> "<esc>x: emmet<ret>"

plug "occivink/kakoune-sudo-write"
plug "eraserhd/kak-ansi"

eval %sh{kak-lsp --kakoune -s $kak_session --config /home/utter/.config/kak-lsp/kak-lsp.toml}
    hook global WinSetOption filetype=(python|html|javascript|typescript|css) %{
    lsp-enable-window
}
set-option global lsp_config %{
    [language.python.settings._]
    "pyls.configurationSources" = ["flake8"]
}
lsp-auto-hover-enable
set global lsp_hover_anchor true
map global normal ä %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
# plug "kakounedotcom/connect.kak"
# source "~/.config/kak/plugins/connect/connect.kak"
# source "~/.config/kak/plugins/connect/modules/nnn/nnn.kak"
# require-module connect
plug "kakounedotcom/prelude.kak"
# plug "alexherbo2/connect.kak" %{
  # require-module connect-nnn
  # require-module connect-fzf
# }
evaluate-commands %sh{
  kcr init kakoune
}

# map -docstring 'new client' global normal <c-t> ': new<ret>'
# map -docstring 'terminal (popup)' global normal <c-ret> ': connect terminal-popup<ret>'
# map -docstring 'git (popup)' global normal <c-l> ': connect terminal-popup gitui<ret>'
# map -docstring 'file explorer' global normal <c-e> ': connect terminal-panel sidetree --select %val{buffile}<ret>'
map -docstring 'file picker' global user v ': connect terminal kcr fzf files<ret>'
map -docstring 'buffer picker' global user m ': connect terminal-tab kcr fzf buffers<ret>'
map -docstring 'grep picker' global user j ': connect terminal-tab kcr fzf grep<ret>'
map -docstring 'grep picker (buffer)' global user x ': connect terminal kcr fzf grep %val{buflist}<ret>'
# require-module connect-nnn
# Explore files with nnn
# alias global explore-files nnn
# alias global explore-buffers fzf-buffers

hook global ModuleLoaded kitty %{
  alias global popup kitty-terminal-tab # or kitty-terminal
  # set global kitty_window_type kitty
}
# set-option global windowing_modules 'x11'
#set-option global auto_pairs ( ) { } [ ] '"' '"' "'" "'" ` ` “ ” ‘ ’ « » ‹ ›

colorscheme berry

# set-face global PrimarySelection white,blue+F
# set-face global SecondarySelection black,blue+F
# set-face global PrimaryCursor black,bright-cyan+F
# set-face global SecondaryCursor black,bright-blue+F
# set-face global PrimaryCursorEol black,bright-cyan
# set-face global SecondaryCursorEol black,bright-blue

# # Shades of green/yellow for insert mode.
# hook global ModeChange (push|pop):.*:insert %{
#     set-face window PrimarySelection white,green+F
#     set-face window SecondarySelection black,green+F
#     set-face window PrimaryCursor black,bright-yellow+F
#     set-face window SecondaryCursor black,bright-green+F
#     set-face window PrimaryCursorEol black,bright-yellow
#     set-face window SecondaryCursorEol black,bright-green
# }

# # Undo colour changes when we leave insert mode.
# hook global ModeChange (push|pop):insert:.* %{
#     unset-face window PrimarySelection
#     unset-face window SecondarySelection
#     unset-face window PrimaryCursor
#     unset-face window SecondaryCursor
#     unset-face window PrimaryCursorEol
#     unset-face window SecondaryCursorEol
# }

add-highlighter global/ number-lines -separator ' ' -hlcursor

# Highlight trailing whitespace
# 
add-highlighter global/ regex \h+$ 0:Error

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Width of a tab
set-option global tabstop 2

# Indent with 4 spaces
set-option global indentwidth 2

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

hook global BufOpenFile .* editorconfig-load
hook global BufNewFile .* editorconfig-load

hook global WinSetOption filetype=diff %{
    map global normal <ret> ': diff-jump<ret>'
}

map global normal t h
map global normal <a-t> <a-h>
map global normal <s-t> <s-h>
map global normal <c-t> <c-h>
map global goto   t h

map global normal n j
map global normal <a-n> pagedown
map global normal <s-n> <s-j>
map global normal <c-n> <c-j>
map global goto   n b
map global goto   N j
map global view   n t

map global normal l k
map global normal <a-l> pageup
map global normal <s-l> <s-k>
map global normal <c-l> <c-k>
map global goto   l t
map global goto   L k
map global view   l b

map global normal s l
map global normal <a-s> <a-l>
map global normal <s-s> <s-l>
map global normal <c-s> <c-l>
map global goto   s l

map global insert <c-t> <esc>bdi 
map global insert <F1> <esc>bi 
map global insert <c-s> <esc>wdi 
map global insert <F3> <esc>Wi 


#space mod
map global normal <F1> b
map global normal <F3> e
map global normal <F2> 'lbe'
map global normal <F4> '<a-;>B<a-;>W'
map global normal <s-F1> B
map global normal <s-F3> W

#h mod
def -params 1 extend-line-down %{
  exec "<a-:>%arg{1}X"
}
def -params 1 extend-line-up %{
  exec "<a-:><a-;>%arg{1}K<a-;>"
  try %{
    exec -draft ';<a-K>\n<ret>'
    exec X
  }
  exec '<a-;><a-X>'
}
map global normal <F6> ':extend-line-down %val{count}<ret>'
map global normal <F8> ':extend-line-up %val{count}<ret>'
map global normal <F5> <a-h>
# map global normal <F6> x
map global normal <F7> <a-l>
#map global normal <F8>
#
map global insert <F6> <c-n> 
map global insert <F8> <c-p> 
map global insert <F5> '<c-n><c-o>'
# map global normal <F6> x
map global insert <F7> <c-o>

#r mod
map global normal <c-F5> ": phantom-selection-iterate-prev<ret>"
map global normal <c-F6> C
map global normal <c-F7> ": phantom-selection-iterate-next<ret>"
map global normal <c-F8> 'kC'
map global insert <c-F7> "<esc>: phantom-selection-iterate-next<ret>i"
map global insert <c-F5> "<esc>: phantom-selection-iterate-prev<ret>i"

map global normal <F9> <a-n> 
# map global normal <F10> ":select<ret>a" 
map global normal <F10> '*%s<ret>' -docstring 'select all'
map global normal <F11> n
map global normal <F12> '*/<ret>'

map global normal <s-F9> <a-N> 
# map global normal <s-F10> n 
map global normal <s-F11> N
# map global normal <s-F12> n

#map global normal tab \>
#map global normal <s-tab> <


#map global normal d b
#map global normal <a-d> <a-b>
#map global normal <s-d> <s-b>
#map global normal <c-d> <c-b>
map global goto   h c
map global view   o v
#
map global normal  u c

#map global normal p w
#map global normal <a-p> <a-w>
#map global normal <s-p> <s-w>
#map global normal <c-p> <c-w>

map global normal \" < 
map global normal \' > 

map global normal a i
map global normal k o
map global normal K <a-o>
map global normal A a
map global normal h g
map global normal H G
map global normal b O
map global normal B <a-O>

# map global normal b n
#map global normal B N

map global normal e /
map global normal E s
map global normal g d
map global normal o v
map global normal Y m
# map global normal y f
#map global normal Y F
map global normal i x
#map global normal I <s-x>
map global normal f u
map global normal F U
map global normal m <space>
map global normal v <semicolon>
# map global normal d y

map global normal <space> ,
# map global normal <s-m> <s-p>
# map global normal <s-t> t

map global normal I <percent>
#swapcase
map global normal <c-i> <a-`> 

map global normal r :
# map global normal ä /

map global normal <space> ,

#hook global normalkey '[dgu]' %{
#  nop %sh{
#    (printf '%s' "$kak_main_reg_dquote" | xclip -filter | xclip -selection clipboard) < /dev/null > /dev/null 2>&1 &
#  }
#}
map global normal d '<a-|>xclip -i -selection clipboard<ret>'
# Paste
map global normal P -docstring 'Paste (After)' '<a-!>xclip -out -selection clipboard<ret>'
map global normal p -docstring 'Paste (Before)' '!xclip -out -selection clipboard<ret>'
map global normal <c-p> -docstring 'Replace' '|xclip -out -selection clipboard<ret>'
# map global normal , <space>
#map global user a ': fzf-mode<ret>'
map global user <space> "gt: easy-motion-w<ret>"
map global user n ": easy-motion-j<ret>"
map global user l ": easy-motion-k<ret>"
map global user ä ": easy-motion-char<ret>"
map global user s ": easy-motion-w<ret>"
map global user t ": easy-motion-b<ret>"

map global normal q ":comment-line<ret>"
map global normal Q ":comment-block<ret>"

map global normal å ":format<ret>"

map global user y ":w<ret>"

declare-user-mode surround
map global surround ö ':surround<ret>' -docstring 'surround'
map global surround c ':change-surround<ret>' -docstring 'change'
map global surround g ':delete-surround<ret>' -docstring 'delete'
map global surround i ':select-surrounding-tag<ret>' -docstring 'select tag'
map global normal ö ':enter-user-mode surround<ret>'
# map global normal ö ':surround<ret>'
# map global normal Ö ':surround-with-tag<ret>'
# map 
# map global user   <a-l>  ':select-surrounding-tag<ret>'
# map global user   <c-l>  ':select-surround<ret>'

#####nnn
# map global user i ':evaluate-commands %sh{kitty --name sidebar -e sh -c "i3-msg move left && i3-msg resize set width 200px && nnn"}<ret> '
# 
map global user h ':connect run kitty --hold sh -c "i3-msg move left && i3-msg resize set width 200px && nnn"}<ret> ' 
map global user i ':connect run kitty <ret> ' 

hook global WinSetOption filetype=html %{
    set-option buffer formatcmd "run(){ tidy -q --indent yes --indent-spaces %opt{tabstop}  2>/dev/null || true; } && run"
}

hook global BufSetOption filetype=css %{
    set-option buffer formatcmd "prettierd --stdin-filepath=%val{buffile}"
}

hook global WinSetOption filetype=javascript %{
  set buffer lintcmd 'eslint --config .eslintrc.js --format=node_modules/eslint-formatter-kakoune'
  lint-enable
  lint
}
# hook global WinSetOption filetype=javascript %{
# 	set buffer lintcmd './node_modules/.bin/eslint --format=node_modules/eslint-formatter-kakoune -c .eslintrc.js'
# 	lint-enable
# }

# define-command -hidden -override move-selection-down %{
    # exec Z d g l p j G L z
# }
# map global normal <c-l> ': move-selection-down<ret>'
define-command -hidden -override move-line-down %{
    exec <a-x> d g l p j g l 
}
define-command -hidden -override move-line-up %{
    exec <a-x> d k P k 
}
map global normal <c-n> ': move-line-down<ret>'
map global normal <c-l> ': move-line-up<ret>'


map global normal j     ": phantom-selection-add-selection<ret>"
map global normal x     ": phantom-selection-select-all; phantom-selection-clear<ret>"
map global normal <s-j> ": phantom-selection-iterate-next<ret>"
map global normal <s-x> ": phantom-selection-iterate-prev<ret>"

map global normal y ': enter-user-mode selectors<ret>' -docstring 'selectors'
map global selectors 'q' '*%s<ret>' -docstring 'select all'

map global selectors 'n' '<a-i>' -docstring 'select inside object <a-i>'
map global selectors 'l' '<a-a>' -docstring 'select outside object <a-a>'

map global selectors 't' '<a-[>' -docstring 'select inner object start <a-[>'
map global selectors 's' '<a-]>' -docstring 'select inner object end <a-]>'
map global selectors 'T' '<a-{>' -docstring 'extend inner object start <a-{>'
map global selectors 'S' '<a-}>' -docstring 'extend inner object end <a-}>'

map global selectors 'e' '[' -docstring 'select object start ['
map global selectors 'u' ']' -docstring 'select object end ]'
map global selectors 'H' '{' -docstring 'extend object start {'
map global selectors 'L' '}' -docstring 'extend object end }'
map global object 'e'    '<esc>: text-object-block (<ret>'    -docstring 'prev parenthesis block'
map global object 'ö'    '<esc>: text-object-block )<ret>'    -docstring 'next parenthesis block'
map global object 'a'    '<esc>: text-object-block {<ret>'    -docstring 'prev braces block'
map global object 'u'    '<esc>: text-object-block }<ret>'    -docstring 'next braces block'
map global object 'g'    '<esc>: text-object-block [<ret>'    -docstring 'prev brackets block'
map global object 'k'    '<esc>: text-object-block ]<ret>'    -docstring 'next brackets block'
map global object 'h' '<esc>: text-object-block <lt><ret>' -docstring 'prev angle block'
map global object 'å' '<esc>: text-object-block <gt><ret>' -docstring 'next angle block'
# additional text objects
map global object 'i'     '<esc>: text-object-line<ret>'               -docstring 'line'
map global object 'h'     '<esc>: text-object-tag<ret>'                -docstring 'tag'
map global object 'b'     '<esc>: text-object-buffer<ret>'             -docstring 'buffer'
map global object '<tab>' '<esc>: text-object-indented-paragraph<ret>' -docstring 'indented paragraph'

