[keybindings]
"n" = "move down 1"
"l" = "move up 1"
"s" = "move right 1"
"t" = "move left 1"
"I" = "queue"
"i" = "open selected"
"T" = "back"
"S" = "forward"
"A" = "goto atist"
"a" = "goto album"
"e" = "search"
" " = "toggleplay"
"N" = "next"
"L" = "previous"
"d" = "share"
"2" = "voldown 5"
"3" = "volup 5"
"Ctrl+s" = "seek +10s"
"p" = "seek +10s"
"Ctrl+t" = "seek -10s"
"f" = "seek -10s"
"g" = "delete"
"h" = "focus cover"
"H" = "focus library"

[theme]
primary = "#CDD6F4"
secondary = "#BAC2DE"
title = "#F5C2E7"
playing = "#A6E3A1"
playing_selected = "#F9E2AF"
playing_bg = "#313244"
highlight = "#CBA6F7"
highlight_bg = "#313244"
error = "#F38BA8"
error_bg = "#313244"
statusbar = "#313244"
statusbar_progress = "#A6E3A1"
statusbar_bg = "#A6E3A1"
cmdline = "#A6ADC8"
cmdline_bg = "#444444"
